notificationChannels:
    - type: "email"
      enabled: false
      displayName: "Dan"
      labels:
          email_address: "danfriedman@google.com"
    - type: "sms"
      enabled: false
      displayName: "Jenny"
      labels:
          number: "212-867-5309"
    - type: "email"
      enabled: false
      displayName: "Syed"
      labels:
          email_address: "ashrafulla@google.com"
    - type: "email"
      enabled: false
      displayName: "Keith"
      labels:
          email_address: "kjordy@google.com"
    - type: "email"
      enabled: false
      displayName: "Abhay"
      labels:
          email_address: "akm@google.com"
    - type: "sms"
      enabled: false
      displayName: "Sir Mix-A-Lot"
      labels:
          number: "1-800-649-2568"

alertPolicies:
    - displayName: 'Non-200 responses too high'
      combiner: OR
      conditions:
        - conditionThreshold:
            filter: 'metric.type="appengine.googleapis.com/http/server/response_count" resource.type=gae_app metric.label.response_code>=300'
            comparison: COMPARISON_GT
            thresholdValue: 100
            duration: 60s
            trigger:
              count: 1
            aggregations:
              - alignmentPeriod: 60s
                perSeriesAligner: ALIGN_RATE
          displayName: 'GAE Application - Response count (filtered)'
      notificationChannels:
        - 'Dan'
      enabled: false
    - displayName: 'KaibaCorp DuelTek not responding'
      combiner: OR
      conditions:
        - conditionThreshold:
            filter: 'resource.type=api resource.labels.service="kaibacorp.googleapis.com" resource.labels.method="DuelTek.GetCard" metric.type="serviceruntime.googleapis.com/api/request_count" metric.label.response_code!=starts_with(2)'
            comparison: COMPARISON_GT
            thresholdValue: 1
            duration: 60s
            trigger:
              count: 1
            aggregations:
              - alignmentPeriod: 3600s
                perSeriesAligner: ALIGN_RATE
          displayName: 'GetCard not responding'
        - conditionThreshold:
            filter: 'resource.type=api resource.labels.service="kaibacorp.googleapis.com" resource.labels.method="DuelTek.CreateCard" metric.type="serviceruntime.googleapis.com/api/request_count" metric.label.response_code!=starts_with(2)'
            comparison: COMPARISON_GT
            thresholdValue: 1
            duration: 60s
            trigger:
              count: 1
            aggregations:
              - alignmentPeriod: 3600s
                perSeriesAligner: ALIGN_RATE
          displayName: 'CreateCard not responding'
      notificationChannels:
        - 'Syed'
      enabled: false
    - displayName: 'Phone Apocalypse'
      combiner: OR
      conditions:
        - conditionThreshold:
            filter: 'resource.type=api resource.labels.service="phone.googleapis.com" resource.labels.method="Phone.Call" metric.type="serviceruntime.googleapis.com/api/request_count" metric.label.response_code!=starts_with(2)'
            comparison: COMPARISON_GT
            thresholdValue: 1
            duration: 60s
            trigger:
              count: 1
            aggregations:
              - alignmentPeriod: 3600s
                perSeriesAligner: ALIGN_RATE
          displayName: 'Call not responding'
        - conditionThreshold:
            filter: 'resource.type=api resource.labels.service="phone.googleapis.com" resource.labels.method="Phone.HangUp" metric.type="serviceruntime.googleapis.com/api/request_count" metric.label.response_code!=starts_with(2)'
            comparison: COMPARISON_GT
            thresholdValue: 1
            duration: 60s
            trigger:
              count: 1
            aggregations:
              - alignmentPeriod: 3600s
                perSeriesAligner: ALIGN_RATE
          displayName: 'HangUp not responding'
      notificationChannels:
        - "Keith"
      enabled: false
    - displayName: 'Secret BitCoin Mining'
      combiner: OR
      conditions:
        - conditionThreshold:
            filter: 'resource.type=api resource.labels.method="BitCoin.Mine" metric.type="serviceruntime.googleapis.com/api/request_count"'
            comparison: COMPARISON_GT
            thresholdValue: 1
            duration: 60s
            trigger:
              count: 1
            aggregations:
              - alignmentPeriod: 3600s
                perSeriesAligner: ALIGN_DELTA
          displayName: 'Mine happened once'
        - conditionThreshold:
            filter: 'resource.type=api resource.labels.method="BitCoin.Transact" metric.type="serviceruntime.googleapis.com/api/request_count"'
            comparison: COMPARISON_GT
            thresholdValue: 2
            duration: 60s
            trigger:
              count: 1
            aggregations:
              - alignmentPeriod: 3600s
                perSeriesAligner: ALIGN_RATE
          displayName: 'Transact happened twice'
      notificationChannels:
        - "Abhay"
      enabled: false
    - displayName: 'CloudSQL is down'
      combiner: OR
      conditions:
        - conditionAbsent:
            filter: 'resource.type=cloudsql_database metric.type="cloudsql.googleapis.com/database/up"'
            duration: 3600s
            trigger:
              count: 1
            aggregations:
              - alignmentPeriod: 60s
                perSeriesAligner: ALIGN_NEXT_OLDER
                crossSeriesReducer: REDUCE_COUNT
          displayName: 'database is not up'
      notificationChannels:
        - "Sir Mix-a-Lot"
      enabled: true
