alertPolicies:
    - name: projects/stacksync/alertPolicies/8939280658919864902
      displayName: 'Non-200 responses too high'
      combiner: OR
      conditions:
        - conditionThreshold:
            filter: 'metric.type="appengine.googleapis.com/http/server/response_count" resource.type="gae_app" metric.label."response_code">="300"'
            comparison: COMPARISON_GT
            thresholdValue: 100
            duration: 60s
            trigger:
              count: 1
            aggregations:
              - alignmentPeriod: 60s
                perSeriesAligner: ALIGN_RATE
          displayName: 'GAE Application - Response count (filtered)'
          name: projects/stacksync/alertPolicies/8939280658919864902/conditions/8939280658919865029
      notificationChannels:
        - projects/stacksync/notificationChannels/5226117608650639874
      enabled: false
