notificationChannels:
    - type: "email"
      enabled: true
      displayName: "danfriedman@google.com"
      labels:
          email_address: "danfriedman@google.com"

alertPolicies:
    - displayName: 'Non-200 responses too high'
      combiner: OR
      conditions:
        - conditionThreshold:
            filter: 'metric.type="appengine.googleapis.com/http/server/response_count" resource.type="gae_app" metric.label."response_code">="300"'
            comparison: COMPARISON_GT
            thresholdValue: 100
            duration: 60s
            trigger:
              count: 1
            aggregations:
              - alignmentPeriod: 60s
                perSeriesAligner: ALIGN_RATE
          displayName: 'GAE Application - Response count (filtered)'
      notificationChannels:
        - "danfriedman@google.com"
      enabled: false
